FlaskBlogApp/__init__.py
from flask import Flask
from flask_simplemde import SimpleMDE
from flask_mongoengine import MongoEngine
from flaskext.markdown import Markdown
from flask_login import LoginManager
from FlaskBlogApp.config import Config

smde = SimpleMDE()
db = MongoEngine()
login_manager = LoginManager()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    smde.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    Markdown(app)

    from FlaskBlogApp.posts.routes import posts
    from FlaskBlogApp.user.routes import user
    from FlaskBlogApp.navigation.routes import navigation
    from FlaskBlogApp.utils import (
        unauthorized_access,
        page_not_found,
        user_loader
    )
    app.register_blueprint(posts)
    app.register_blueprint(user)
    app.register_blueprint(navigation)
    app.register_error_handler(401, unauthorized_access)
    app.register_error_handler(404, page_not_found)

    return app

FlaskBlogApp/navigation/routes.py
from flask import render_template, Blueprint
from flask_login import login_required, current_user
from FlaskBlogApp.posts import Posts

navigation = Blueprint('navigation', __name__)


@navigation.route('/')
def index():
    posts = Posts.objects().all().order_by('-date_posted')
    return render_template('index.html', posts=posts)


@navigation.route('/<string:username>')
@login_required
def index_logged(username):
    posts = Posts.objects().all().order_by('-date_posted')
    return render_template('index.html', posts=posts,
                           username=username)


@navigation.route('/about')
def about():
    return render_template('about.html')


@navigation.route('/contact')
def contact():
    return render_template('contact.html')

FlaskBlogApp/posts/__init__.py
from flask_mongoengine.wtf import model_form
from wtforms import validators

from FlaskBlogApp import db


class Posts(db.Document):
    title = db.StringField(max_length=150,
                           validators=[validators.InputRequired()])
    subtitle = db.StringField(max_length=200,
                              validators=[validators.InputRequired()])
    author = db.StringField(max_length=50,
                            validators=[validators.InputRequired()])
    content = db.StringField(validators=[validators.InputRequired()])
    date_posted = db.DateTimeField()


PostForm = model_form(Posts, field_args={'content': {'textarea': True}})

FlaskBlogApp/posts/routes.py
import datetime

from flask import render_template, request, Blueprint, redirect, url_for, abort
from flask_login import login_required, current_user
from FlaskBlogApp.posts import Posts, PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/<string:post_id>')
def post(post_id):
    post = Posts.objects.get(id=post_id)
    return render_template('post.html', post=post)


@posts.route('/userpost/<string:username>')
@login_required
def user_post(username):
    posts = Posts.objects(author=username).all().order_by('-date_posted')
    return render_template('my_posts.html', posts=posts, username=username)


@posts.route('/add', methods=['GET', 'POST'])
@login_required
def addpost():
    if request.method == 'GET':
        form = PostForm(request.form)
        return render_template('add.html', form=form)
    else:
        post = Posts(title=request.form['title'],
                     subtitle=request.form['subtitle'],
                     author=current_user.username,
                     content=request.form['content'],
                     date_posted=datetime.datetime.now())
        post.save()

        return redirect(url_for('posts.post', post_id=post.pk))


@posts.route('/edit/<string:post_id>', methods=['GET', 'POST'])
@login_required
def editpost(post_id):
    post = Posts.objects.get(id=post_id)
    if request.method == 'GET':
        if current_user.username != post.author:
            abort(401)
        form = PostForm(request.form)
        return render_template('add.html', form=form, post=post)
    else:
        Posts.objects(id=post.id).update(title=request.form['title'],
                                         subtitle=request.form['subtitle'],
                                         author=current_user.username,
                                         content=request.form['content'],
                                         date_posted=datetime.datetime.now())
        post.reload()

        return redirect(url_for('posts.post', post_id=post.pk))


@posts.route('/delete/<string:post_id>')
@login_required
def deletepost(post_id):
    post = Posts.objects.get(id=post_id)
    if current_user.username != post.author:
        abort(401)
    post.delete()
    return redirect(url_for('posts.user_post', username=current_user.username))

FlaskBlogApp/user/__init__.py
from flask_mongoengine.wtf import model_form
from wtforms import validators

from FlaskBlogApp import db


class User(db.Document):
    username = db.StringField(required=True, max_length=50,
                              validators=[validators.InputRequired()])
    password = db.StringField(required=True,
                              validators=[validators.InputRequired()])
    authenticated = db.BooleanField()

    def is_active(self):
        return True

    def get_id(self):
        return self.username

    def is_authenticated(self):
        return self.authenticated

    def is_anonymous(self):
        return False

    @classmethod
    def get_user_by_username(cls, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        else:
            return user


UserForm = model_form(User, field_args={'password': {'password': True}})

FlaskBlogApp/user/routes.py
import os
from werkzeug.security import generate_password_hash, check_password_hash
from flask import (
    Blueprint, request, render_template, redirect, url_for, abort
)
from flask_login import (
    login_required, current_user, logout_user, login_user
)

from FlaskBlogApp.user import User, UserForm

user = Blueprint('user', __name__)


@user.route('/signup', methods=['GET', 'POST'])
def signup():
    if not os.environ.get('SIGNUP_ENABLED', True):
        abort(401)
    form = UserForm(request.form)
    if request.method == 'GET':
        return render_template('login.html', form=form, type='SignUp')
    else:
        if User.get_user_by_username(username=request.form['username']):
            return render_template('login.html', form=form, type='SignUp',
                                   error="A user with username already exists")
        else:
            user = User(username=request.form['username'],
                        password=generate_password_hash(request.form['password']),
                        authenticated=False)
            user.save()
            return redirect(url_for('user.login'))


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = UserForm(request.form)
    if request.method == 'GET':
        return render_template('login.html', form=form, type='Login')
    else:
        user = User.get_user_by_username(username=request.form['username'])
        if user and check_password_hash(user.password, request.form['password']):
            user.authenticated = True
            user.save()
            login_user(user, remember=True)
            return redirect(url_for('navigation.index_logged',
                                    username=user.username))
        else:
            return render_template('login.html', form=form, type='Login',
                                   error="Invalid Credentials")


@user.route('/logout', methods=['GET'])
@login_required
def logout():
    user = current_user
    user.authenticated = False
    user.save()
    logout_user()
    return redirect(url_for('navigation.index'))

FlaskBlogApp/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block image %}{{ url_for( 'static', filename='about-bg.jpg')}}{% endblock %}
{% block header %}
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">This is what I do.</span>
            </div>
{% endblock %}
{% block content %}
	<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Hey everyone !!! My name is Rishi Deorukhkar and I am from Mumbai.
             I have been working as a software developer since 2015.
             Programming mainly in C, C++, Python and Unix shell.</p>
          <p>In the recent years I have grown really fond of programming in Python.
             On this blog site I will be posting some of my Python and other hobby projects
             which I have been working on.</p>
        </div>
      </div>
    </div>
{% endblock %}

FlaskBlogApp/templates/add.html
{% extends "base.html" %}
{% block title %}Add post{% endblock %}
{% block image %}{{ url_for( 'static', filename='post-bg.jpg')}}{% endblock %}
{% block header %}
            <div class="page-heading">
              <h1>My Posts</h1>
            </div>
{% endblock %}
{% block head %}
    {{ simplemde.css }}
    {{ simplemde.js }}
    <script>
    function ValidationEvent() {
      var title = document.forms["addForm"]["title"].value;
      var subtitle = document.forms["addForm"]["subtitle"].value;
      var content = document.forms["addForm"]["content"].value;
      if (title == "") {
        alert("Title cannot be empty");
        return false;
      }
      if (subtitle == "") {
        alert("Subtitle cannot be empty");
        return false;
      }
      if (content == "") {
        alert("Content cannot be empty")
        return false
      }
    }
    </script>
    <script>
    {% if post %}
    window.onload = function(){
      document.getElementById("title").value = "{{post.title}}";
      document.getElementById("subtitle").value = "{{post.subtitle}}";
    }
    {% endif %}
    </script>
{% endblock %}
{% block content %}
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <form name="addForm" id="addForm" method="POST" onsubmit="return ValidationEvent()" action="" novalidate>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                {{ form.title.label }} {{ form.title(class="form-control", placeholder="Title") }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                {{ form.subtitle.label }} {{ form.subtitle(class="form-control", placeholder="Subtitle") }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label for="content">content</label> 
                <textarea class="form-control" id="content" name="content" placeholder="Blog Content" required>
                {% if post %}    
                {{post.content}}
                {% endif %}
                </textarea>
                <script>
                (function () {
                  var simplemde = new SimpleMDE({ element: document.getElementById("content") });
                })();
                </script>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button class="btn btn-primary" id="sendMessageButton"> 
                  Submit
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock %}

FlaskBlogApp/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for( 'static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for( 'static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for( 'static', filename='clean-blog.min.css') }}" rel="stylesheet">
    {% block head %}
    {% endblock %}
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    
      <div class="container">
              {% if current_user.is_authenticated %}
              <a class="navbar-brand" href="{{ url_for('navigation.index_logged', username=username) }}">Blog</a>
              {% else %}
              <a class="navbar-brand" href="{{ url_for('navigation.index') }}">Blog</a>
              {% endif %}
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              {% if current_user.is_authenticated %}
              <a class="navbar-brand" href="{{ url_for('navigation.index_logged', username=username) }}">Home</a>
              {% else %}
              <a class="navbar-brand" href="{{ url_for('navigation.index') }}">Home</a>
              {% endif %}
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.user_post', username=current_user.username) }}">My Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.addpost') }}">Add Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('navigation.about') }}">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% block image %}{% endblock %}')">  
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {% block header %}
            {% endblock %}
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    {% block content %}
    {% endblock %}

    {% if posts %}
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{{ url_for('posts.post', post_id=post.pk) }}">
              <h2 class="post-title">
                {{ post['title'] }}
              </h2>
              <h3 class="post-subtitle">
                {{ post['subtitle'] }}
              </h3>
            </a>
            <p class="post-meta">Posted by
              {{ post['author'] }}
              on {{ post['date_posted'].strftime("%B %d, %Y") }}</p>
          </div>
          <hr>
        {% endfor %}
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

    <hr>

    <!-- Footer -->
    
    <footer> 
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/rishideorukhkar">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/rishi.deorukhkar">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/RishiSD">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Built by yoshirishi
            <br>
            <em>Go Boldly Forward</em></p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for( 'static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='bootstrap.bundle.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for( 'static', filename='clean-blog.min.js') }}"></script>

  </body>

</html>

FlaskBlogApp/templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title> {{ error }} </title>

	<link href="{{ url_for( 'static', filename='bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for( 'static', filename='font-awesome.min.css') }}" rel="stylesheet">
	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{{ url_for( 'static', filename='error.css') }}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-401">
				<h3>{{ err_text }}</h3>
				<h1><span>{{ error[0] }}</span><span>{{ error[1] }}</span><span>{{ error[2] }}</span></h1>
			</div>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

FlaskBlogApp/templates/index.html
{% extends "base.html" %}
{% block title %}Rishi's Blog{% endblock %}
{% block image %}{{ url_for( 'static', filename='home-bg.jpg')}}{% endblock %}
{% block header %}
            <div class="site-heading">
              <h1>Rishi's Blog</h1>
              <span class="subheading">A Blog Site by programming enthusiast</span>
            </div>
{% endblock %}

FlaskBlogApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ type }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='bootstrap.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='material-design-iconic-font.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='animate.css') }}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='hamburgers.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='animsition.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='select2.min.css') }}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='daterangepicker.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='main.css') }}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-85 p-b-20">
				<form name="LoginForm" id="LoginForm" class="login100-form validate-form"  method="POST" >
					<span class="login100-form-title p-b-70">
						Welcome to Rishi's Blog
					</span>
					<div align="center">
						{% if error %}
							<p2 style="color:red;"> {{ error }} </p2>
						{% endif %}
					</div>	
					<div class="wrap-input100 validate-input m-t-85 m-b-35" data-validate = "Enter username">
						{{ form.username.label }} {{ form.username(class="input100") }}
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-50" data-validate="Enter password">
						{{ form.password.label }} {{ form.password(class="input100", type="password") }}
						<span class="focus-input100"></span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							{{ type }}
						</button>
					</div>
					<br>							
					
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='animsition.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='popper.js') }}"></script>
	<script src="{{ url_for( 'static', filename='bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='moment.min.js') }}"></script>
	<script src="{{ url_for( 'static', filename='daterangepicker.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='countdowntime.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='main.js') }}"></script>

</body>
</html>

FlaskBlogApp/templates/my_posts.html
{% extends "base.html" %}
{% block title %}My Posts{% endblock %}
{% block image %}{{ url_for( 'static', filename='post-bg.jpg')}}{% endblock %}
{% block header %}
            <div class="page-heading">
              <h1>My Posts</h1>
            </div>
{% endblock %}

FlaskBlogApp/templates/post.html
{% extends "base.html" %}
{% block title %}Post{% endblock %}
{% block image %}{{ url_for( 'static', filename='post-bg.jpg')}}{% endblock %}
{% block header %}
          <div class="post-heading">
             <h1>{{ post.title }}</h1>
            <h2 class="subheading">{{ post.subtitle }}</h2>
            <span class="meta">Posted by {{ post.author }} on {{ post.date_posted.strftime("%B %d, %Y") }}</span>
          </div>
{% endblock %}
{% block head %}
    <script>
    function subConfirm() {  
      res = confirm("Are you sure you want to delete the post ?");
      if (res == true) {
        window.location.href = "{{ url_for('posts.deletepost', post_id=post.pk) }}";
      }
    }
    </script>
{% endblock %}
{% block content %}
    {% if current_user.is_authenticated and current_user.username == post.author %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto"> 
        <a href="{{ url_for('posts.editpost', post_id=post.pk) }}" class="btn btn-primary">Edit</a>
        <input type="button" class="btn btn-primary" onclick="subConfirm()" value="Delete" />
      </div>
    </div>
    <br>
    <br>
    {% endif %}
    <article>
      <div class="container"  >
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.content | markdown }}
          </div>
        </div>
      </div>
    </article>
{% endblock %}